.onLoad <- function(lib, pkg){

  packageStartupMessage("\n")
  packageStartupMessage("######################################################################################\n")
  packageStartupMessage("\n")
  packageStartupMessage("Have fun with GLAD\n")
  packageStartupMessage("\n")  
  packageStartupMessage("For smoothing it is possible to use either\n")
  packageStartupMessage("the AWS algorithm (Polzehl and Spokoiny, 2002)\n")
  packageStartupMessage("or the HaarSeg algorithm (Ben-Yaacov and Eldar, Bioinformatics,  2008)\n")
  packageStartupMessage("\n")
  packageStartupMessage("If you use the package with AWS, please cite:\n")
  packageStartupMessage("Hupe et al. (Bioinformatics, 2004) and Polzehl and Spokoiny (2002)\n")
  packageStartupMessage("\n")    
  packageStartupMessage("If you use the package with HaarSeg, please cite:\n")
  packageStartupMessage("Hupe et al. (Bioinformatics, 2004) and (Ben-Yaacov and Eldar, Bioinformatics, 2008)\n")
  packageStartupMessage("\n")
  packageStartupMessage("For fast computation it is recommanded to use\n")
  packageStartupMessage("the daglad function with smoothfunc=haarseg\n")
  packageStartupMessage("\n")
  packageStartupMessage("######################################################################################\n")    
  packageStartupMessage("\n")
  packageStartupMessage("New options are available in daglad: see help for details.")
  packageStartupMessage("\n")  
    
}
